### ISSUE TITLE
Examples to execute specific scenarios

### ISSUE THREAD

**Issue by SSMK-wq** [fschaeck/python-pptx-text-replacer#1]
Hi Frank,

Thanks a lot for this package. I am counting on this a lot. I have a humble request. By any chance, is it possible for you to prepare user guide on how to use it? May be too much to ask. I value your time and can also support by paying 25USD for this task. Would this be interesting to you? I seriously appreciate your effort but am unable to execute correctly because (am not a coder) and hard to understand the code and how to pass parameters. But I am sure for you this must be easy to prepare in a day or two (because you know how code works). While preparing user guide, is it possible to keep jupyter notebook in mind?

I tried something like below but I got the below error message (due to incorrect passing of inputs)

![image](https://user-images.githubusercontent.com/30723825/183879094-7811188a-431b-42df-a63e-1a707a5abb93.png)

By any chance, is it possible for you to prepare user guide on below scenarios?

a) How to run this code for replacing one term with another (ex: FY2021 replaced as FY2122)

b) How to run this code for replacing multiple terms with multiple terms ([FY2021 replaced as FY2122, FY1918 replaced as FY2019, etc]

c) How to replace only in Charts and chart labels

d) How to replace only in tables and tables headers

e) How to replace only in textframes of all shapes and sizes

I know you have a lot of other parameter options as well (but for the sake of my use case, above scenarios are to be executed and can't wait to try your tool). I am sincerely hoping it helps and your effort is appreciated.

**Comment by fschaeck** [comment]
I updated the script to support your scenarios and updated the README.md file with examples according to your scenarios. Hope that explains everything with enough detail for you to get it working the way you need it.

In any case, you should not change the code in the file python_pptx_text_replacer.py at all! Create your own Python script and import the python_pptx_text_replacer just like shown in the second list of the examples.
