### ISSUE TITLE
ValueError: `.target_part` property on _Relationship is undefined when target-mode is external

### ISSUE THREAD

**Issue by SSMK-wq** [fschaeck/python-pptx-text-replacer#5]
I managed to install and execute the package successfully but I got the below error. Please find full error message

I think the issue is happening under chart type and category types. If I turn off charts, it works fine. But with charts turned on, it threw the below error

```
Slide[8, id=307] with title '<no title>'
    Shape[0, id=17, type=CHART (3)]
      Chart of type COLUMN_STACKED (52)
        Category[0] 'FY17/18 
``` 
       
**It works fine and print messages fine till end of Category[3] but once it enters Category[4], after printing few messages, it throws this error** 

```
----> 3 replacer.replace_text([('FY21/22','FY22/23'),('FY_2021','FY21/22'),('FY20/21','FY21/22'),('GA2021','GA2022'),
      4                        ('GA2020','GA2022'),('SEP-2022','SEP-2023'),('SEP-2021','SEP-2022'),('OCT-2021','OCT-2022'),
      5                        ('OCT-2020','OCT-2021'),('OCT 2021','OCT 2022'),('NOV 2021','NOV 2022'),('FY2122','FY22/23'),

~\Anaconda3\lib\site-packages\python_pptx_text_replacer\TextReplacer.py in replace_text(self, replacements)
    119             print("  Slide[%s, id=%s] with title '%s'" % ( slide_idx+1, slide.slide_id, "<no title>" if slide.shapes.title is None else slide.shapes.title.text ))
    120             if self._slides[slide_idx]:
--> 121                 self._process_shapes(2, slide)
    122             else:
    123                 print("    ... skipped")

~\Anaconda3\lib\site-packages\python_pptx_text_replacer\TextReplacer.py in _process_shapes(self, level, shape_list_parent)
    321                         for series in chart.series:
    322                             new_chart_data.add_series(series.name,series.values)
--> 323                         chart.replace_data(new_chart_data)
    324                 else:
    325                     print("%s... skipped" % ( "  "*(level+2)))

~\Anaconda3\lib\site-packages\pptx\chart\chart.py in replace_data(self, chart_data)
    169         rewriter = SeriesXmlRewriterFactory(self.chart_type, chart_data)
    170         rewriter.replace_series_data(self._chartSpace)
--> 171         self._workbook.update_from_xlsx_blob(chart_data.xlsx_blob)
    172 
    173     @lazyproperty

~\Anaconda3\lib\site-packages\pptx\parts\chart.py in update_from_xlsx_blob(self, xlsx_blob)
     61         there isn't one.
     62         """
---> 63         xlsx_part = self.xlsx_part
     64         if xlsx_part is None:
     65             self.xlsx_part = EmbeddedXlsxPart.new(xlsx_blob, self._chart_part.package)

~\Anaconda3\lib\site-packages\pptx\parts\chart.py in xlsx_part(self)
     78             None
     79             if xlsx_part_rId is None
---> 80             else self._chart_part.related_part(xlsx_part_rId)
     81         )
     82 

~\Anaconda3\lib\site-packages\pptx\opc\package.py in related_part(self, rId)
     44     def related_part(self, rId):
     45         """Return related |Part| subtype identified by `rId`."""
---> 46         return self._rels[rId].target_part
     47 
     48     def target_ref(self, rId):

~\Anaconda3\lib\site-packages\pptx\util.py in __get__(self, obj, type)
    213             # ---and store that value in the (otherwise unused) host-object
    214             # ---__dict__ value of same name ('fget' nominally)
--> 215             value = self._fget(obj)
    216             obj.__dict__[self.__name__] = value
    217         return value

~\Anaconda3\lib\site-packages\pptx\opc\package.py in target_part(self)
    702         """|Part| or subtype referred to by this relationship."""
    703         if self.is_external:
--> 704             raise ValueError(
    705                 "`.target_part` property on _Relationship is undefined when "
    706                 "target-mode is external"

ValueError: `.target_part` property on _Relationship is undefined when target-mode is external


```

**Comment by fschaeck** [comment]
I think this error stems from the fact, that your chart is using external data which probably needs to be handled differently than internal data. Remember, I need to re-create the data series for python-pptx to be able to overwrite the category texts. And for that chart that does not seem possible.

Is there any way you could attach this one slide containing the chart in question here? Possibly erasing everything else on that slide as well in case it would contain confidential information. I really need to look at that chart closer to be able to figure out what could be done.

**Comment by SSMK-wq** [comment]
@fschaeck  - Yes, I remember your other response to SO post to update chart headers. Upon inspecting, I found that though PPT has charts that has headers (coming from some excel data) but the excel file itself is missing(there is a linking issue).

When I try to `Edit data in Excel` or just `Edit Data` in PPT (by right clicking the chart), I get the below error

![image](https://user-images.githubusercontent.com/30723825/184528130-29187996-ee81-4bb0-b33c-6ce957b60b2e.png)

I really appreciate your help but the problem is my office laptop doesn't allow to upload files (outside office network). I can't even open google drive. Hence, am not able to share file but I can share screenshot of how the slide looks. Not sure, whether the below can help

![image](https://user-images.githubusercontent.com/30723825/184528961-3dd8076d-11d5-4694-844c-3daa006714d4.png)



But the question that I have is, i think your code works fine but for some reason it throws the error only for Category[4]  but it works fine for Category[0],Category[1],Category[2],Category[3]. 

Does your textreplacer also replace chart headers (with embedded data in it)? If No, then why does it throw error only for Category[4] and not for other categories?

Also, please find full print message (for that chart)

```
Slide[8, id=307] with title '<no title>'
    Shape[0, id=17, type=CHART (3)]
      Chart of type COLUMN_STACKED (52)
        Category[0] 'FY17/18
Actual € M'
          Replacing 'FY21/22' -> no match
          Replacing 'FY_2021' -> no match
          Replacing 'FY20/21' -> no match
          Replacing 'GA2021' -> no match
          Replacing 'GA2020' -> no match
          Replacing 'SEP-2022' -> no match
          Replacing 'SEP-2021' -> no match
          Replacing 'OCT-2021' -> no match
          Replacing 'OCT-2020' -> no match
          Replacing 'OCT 2021' -> no match
          Replacing 'NOV 2021' -> no match
          Replacing 'FY2122' -> no match
          Replacing 'FY2021' -> no match
          Replacing 'FY1920' -> no match
          Replacing 'FY_2122' -> no match
          Replacing 'FY21/22 / FY22/23' -> no match
          Replacing 'F21Y22' -> no match
          Replacing 'your FY20 POS FCST' -> no match
          Replacing 'your FY21/22 POS FCST' -> no match
          Replacing 'Q2/FY22/23' -> no match
          Replacing 'JAN-22' -> no match
          Replacing 'FY19/20' -> no match
        Category[1] 'FY18/19
Actual € M'
          Replacing 'FY21/22' -> no match
          Replacing 'FY_2021' -> no match
          Replacing 'FY20/21' -> no match
          Replacing 'GA2021' -> no match
          Replacing 'GA2020' -> no match
          Replacing 'SEP-2022' -> no match
          Replacing 'SEP-2021' -> no match
          Replacing 'OCT-2021' -> no match
          Replacing 'OCT-2020' -> no match
          Replacing 'OCT 2021' -> no match
          Replacing 'NOV 2021' -> no match
          Replacing 'FY2122' -> no match
          Replacing 'FY2021' -> no match
          Replacing 'FY1920' -> no match
          Replacing 'FY_2122' -> no match
          Replacing 'FY21/22 / FY22/23' -> no match
          Replacing 'F21Y22' -> no match
          Replacing 'your FY20 POS FCST' -> no match
          Replacing 'your FY21/22 POS FCST' -> no match
          Replacing 'Q2/FY22/23' -> no match
          Replacing 'JAN-22' -> no match
          Replacing 'FY19/20' -> no match
        Category[2] 'FY19/20
Actual € M'
          Replacing 'FY21/22' -> no match
          Replacing 'FY_2021' -> no match
          Replacing 'FY20/21' -> no match
          Replacing 'GA2021' -> no match
          Replacing 'GA2020' -> no match
          Replacing 'SEP-2022' -> no match
          Replacing 'SEP-2021' -> no match
          Replacing 'OCT-2021' -> no match
          Replacing 'OCT-2020' -> no match
          Replacing 'OCT 2021' -> no match
          Replacing 'NOV 2021' -> no match
          Replacing 'FY2122' -> no match
          Replacing 'FY2021' -> no match
          Replacing 'FY1920' -> no match
          Replacing 'FY_2122' -> no match
          Replacing 'FY21/22 / FY22/23' -> no match
          Replacing 'F21Y22' -> no match
          Replacing 'your FY20 POS FCST' -> no match
          Replacing 'your FY21/22 POS FCST' -> no match
          Replacing 'Q2/FY22/23' -> no match
          Replacing 'JAN-22' -> no match
          Replacing 'FY19/20' -> changed to 'FY20/21
Actual € M'
        Category[3] 'FY20/21
Actual € M'
          Replacing 'FY21/22' -> no match
          Replacing 'FY_2021' -> no match
          Replacing 'FY20/21' -> changed to 'FY21/22
Actual € M'
          Replacing 'GA2021' -> no match
          Replacing 'GA2020' -> no match
          Replacing 'SEP-2022' -> no match
          Replacing 'SEP-2021' -> no match
          Replacing 'OCT-2021' -> no match
          Replacing 'OCT-2020' -> no match
          Replacing 'OCT 2021' -> no match
          Replacing 'NOV 2021' -> no match
          Replacing 'FY2122' -> no match
          Replacing 'FY2021' -> no match
          Replacing 'FY1920' -> no match
          Replacing 'FY_2122' -> no match
          Replacing 'FY21/22 / FY22/23' -> no match
          Replacing 'F21Y22' -> no match
          Replacing 'your FY20 POS FCST' -> no match
          Replacing 'your FY21/22 POS FCST' -> no match
          Replacing 'Q2/FY22/23' -> no match
          Replacing 'JAN-22' -> no match
          Replacing 'FY19/20' -> no match
        Category[4] 'FY21/22
FCST € M'
          Replacing 'FY21/22' -> changed to 'FY22/23
FCST € M'
          Replacing 'FY_2021' -> no match
          Replacing 'FY20/21' -> no match
          Replacing 'GA2021' -> no match
          Replacing 'GA2020' -> no match
          Replacing 'SEP-2022' -> no match
          Replacing 'SEP-2021' -> no match
          Replacing 'OCT-2021' -> no match
          Replacing 'OCT-2020' -> no match
          Replacing 'OCT 2021' -> no match
          Replacing 'NOV 2021' -> no match
          Replacing 'FY2122' -> no match
          Replacing 'FY2021' -> no match
          Replacing 'FY1920' -> no match
          Replacing 'FY_2122' -> no match
          Replacing 'FY21/22 / FY22/23' -> no match
          Replacing 'F21Y22' -> no match
          Replacing 'your FY20 POS FCST' -> no match
          Replacing 'your FY21/22 POS FCST' -> no match
          Replacing 'Q2/FY22/23' -> no match
          Replacing 'JAN-22' -> no match
          Replacing 'FY19/20' -> no match
          Error from here
```

**Comment by fschaeck** [comment]
The reason, the error happens after category 4 is simply, that the program is first changing all the category texts (and there are obviously 4 of them in that chart) and only if at the end any actually changed is it trying to recreate the data series with the new category names. The problem you have here is exactly what you see when you try to change the data inside PowerPoint. The data is just not available and that is why recreating the data series is failing. There might be some graceful way out, but I will have to create a chart with exactly that problem myself first. Might take a bit. You are probably better off, excluding that slide through the '—slides' parameter or changing the category names by hand so the program doesn’t need to do anything with it.

**Comment by SSMK-wq** [comment]
I turned off the charts (set them to False) but I realized that it still
replaces chart headers (where there is textboxes for chart headers). Those
work fine. Yeah, understand, it is due to lack of excel file.

Even manually I don't find that excel (and I will check with the owner why
is excel missing). So, you mean to say that if embedded excel is found
(upon right click), it would not throw this error. Am I right?

**Comment by fschaeck** [comment]
Yes, I would expect, that if the excel file is present, there won’t be any issue changing the category names in the chart. But as I said, I am going to test that with a self-constructed chart from an Excel file and see how that goes.

I started to assemble unit test anyway and will make that one of the tests.

**Comment by SSMK-wq** [comment]
Instead of error, is it possible to skip such charts (with excel file
missing warning message in some color to highlight) that it is missed and
move onto the next charts amd complete the execution successfully?

**Comment by fschaeck** [comment]
I looked at the code of the pptx package and it is clear, that even if the external Excel file is available, replacing the data - and with it the category names - won’t work. For external charts like that one, there is no access to the place where the data is stored - and thus can not be replaced either.

I‘ll change my code to handle that error gracefully with an error message and I‘ll change the warning and error messages to be printed to stderr instead of stdout for easier recognition - because I certainly won’t be opening the can of worms of trying to print colored messages and then getting one issue after the other because that doesn’t work in this and that and those environments.

I may even repeat those messages at the very end so they can’t be overlooked.

**Comment by SSMK-wq** [comment]
Sure. Okay. So, to replace chart headers, we should follow your SO response
approach. Am I right? So, in your 0.0.3 package, charts = True will replace
headers which are stored in text boxes (and has no embedded excel in it).
So, I understoodbthe functiinality. Right?

**Comment by fschaeck** [comment]
I just pushed version 0.0.4 to PyPI that will handle the ValueError on chart data replacement gracefully and will print all warnings and error messages at the end to stderr again. The warnings and error message go out to stdout during the actual replacement process to have the messages appear in their right context. The printout to stderr at the end is in addition to that.

I don't know, what you mean with chart headers. My program only changes chart categories in any chart. I presume, what you call chart headers are in fact text boxes grouped with the chart but not really belonging to the chart?!? charts=False will ONLY prevent chart categories from being changed and that is - to my knowledge - anyway the only text appearing in charts. Any text frames on or around the chart will still be processed (except - naturally - if you also specify textframes=False).
