### ISSUE TITLE
suppress print outputs and reduce execution time?

### ISSUE THREAD

**Issue by SSMK-wq** [fschaeck/python-pptx-text-replacer#8]
The print message is very useful for me to know how python-pptx is reading the text and storing it etc.

However, let's say if a business users uses this tool, I think they don't have to see how it is working underneath etc.

This also increases execution time etc.  Is there anyway to hide the print out (thereby making it work faster)?

Is the only way to do this is below

a) Go to source code and comment print lines? So, I can reduce the execution time? 

b) I was going through this [here in SO](https://stackoverflow.com/questions/8391411/how-to-block-calls-to-print) but doesn't help

I ask because with print statement it is taking around 16s for one of my PPTs but without print statements, it is taking only 4.3 s

So, thought of checking with you. Of course, if we can't do this, it is fine. Am still grateful for the package developed and it is really useful

**Comment by fschaeck** [comment]
I can add a '--verbose' option, that will make the script do the print lines and if it is absent only the error messages would be printed at the end. Would that fit your needs?

**Comment by SSMK-wq** [comment]
Yes.

**Comment by fschaeck** [comment]
I just uploaded version 0.0.5 which gives you two additional options. If you use --verbose, it will print the structure of the presentation file and all the changes done (just as it has been doing before). If you do not specify --verbose, it will only print the changes being done. And with the option --quiet you can suppress even that output as well. If you specify --verbose AND --quiet, --verbose is taking precedence.

Hope that helps.

**Comment by SSMK-wq** [comment]
I know for command line options we can use --verbose etc. But in jupyter
notebook, should we set verbose = True?

**Comment by fschaeck** [comment]
Yes… on the call to TextReplacer.replace_text(…,verbose=True,quiet=False)

I will have to put that into the README.md as well…

**Comment by SSMK-wq** [comment]
@fschaeck  - I tried verbose and quiet options (with latest version) but it still displays print messages like it was earlier.

whether I set verbose=True or False, it still shows all print messages like earlier.  I did the below

```
%%time
replacer = TextReplacer("BIZ.pptx", slides='',
                                     tables=True, charts=False, textframes=True,verbose=False,quiet=True)
```

I also tried different combinations of values for verbose and quiet but still it shows all print messages. Can I seek your help for this if you have time?

**Comment by fschaeck** [comment]
I presume, your mistake was to use verbose=False when creating the TextReplacer object and verbose=True when calling TextReplacer.replace_text. There was actually no verbose and quiet parameter on TextReplacer(...) but there was no error message given, when they were specified either.

I uploaded version 0.0.6 which now allows to specify verbose and quiet when creating the TextReplacer object (default for both parameters is False). Those will then be used as defaults for TextReplacer.replace_text(...) if no parameters verbose and/or quiet are given in the call.

If verbose=True is in effect - either through the default from TextReplacer(...,verbose=True) or given in the call to TextReplacer.replace_text(...,verbose=True) - the parameter quiet is ignored!

But pay attention: even if you create the TextReplacer object with TextReplacer(..., verbose=False, quiet=True), you will still get ALL the output if you call TextReplacer.replace_text with verbose=True!
